services:
  mysql:
    container_name: db_teste_serasa
    image: 'mysql:8.0.44'
    environment:
      - 'MYSQL_DATABASE=db_teste_serasa'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=serasadb'
    ports:
      - '3306:3306'
